---
services:
- mongodb
after_success: ./script/deploy-heroku.rb
env:
  global:
  - secure: ! 'JdgPZMRUXWwRY5mSUKOqGv8xpz51ImB1hhxVkdcb9Sf4XjJ91Lz2HNpva8Go

      vZfaTXuCvrs8GP0Yfvh3NKgm0GI3zsuKbKbtfAAwKfBS1kHaJZ28iOWXlsGD

      KcG/qgOzs5Z7iJfy2cnCu3x6OQMTduu1PuThcLhL5D/mjKi6fj8='
